// <auto-generated />
using System;
using IdentitySeries.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentitySeries.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IdentitySeries.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Position")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new { Id = new Guid("e310a6cb-6677-4aa6-93c7-2763956f7a97"), Age = 26, Name = "Mark Miens", Position = "Software Developer" },
                        new { Id = new Guid("398d10fe-4b8d-4606-8e9c-bd2c78d4e001"), Age = 29, Name = "Anna Simmons", Position = "Software Developer" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
